#ifndef Interface_IDL
#define Interface_IDL

module Interface_lsodtrp3 {

    struct AnswerStruct{
	    long error;
	    long server_error;
	    string answer;
	};

    struct requestNuevo {
        string designation;
        long maximum;
        string key_client;
    };

    struct requestQuita {
       short code;
       string key_client;
    };

    struct requestInscribe {
       string name;
       string alias;
    };

    struct requestPlantilla {
       string key_client;
    };

    struct requestRepertorio {
       octet minimum;
    };

    struct requestJuega {
       string alias;
       short code;
    };

    struct requestTermina {
       string alias;
       short code;
    };

    struct requestLista {
       short code;
    };

    interface lsodtrp3 {

        void nuevo(in requestNuevo request, out AnswerStruct response);
        void quita(in requestQuita request, out AnswerStruct response);
        void inscribe(in requestInscribe request, out AnswerStruct response);
        void plantilla(in requestPlantilla request, out AnswerStruct response);
        void repertorio(in requestRepertorio request, out AnswerStruct response);
        void juega(in requestJuega request, out AnswerStruct response);
        void termina(in requestTermina request, out AnswerStruct response);
        void lista(in requestLista request, out AnswerStruct response);
    };
};
#endif
