#ifndef Interface_lsodtrp3
#define Interface_lsodtrp3

module Interface_lsodtrp3 {

    struct Answer{
	    short error;
	    short server_error;
	    string answer;
	};

    struct requestNuevo {
        string designation;
        long maximum;
        string key_client;
    };

    struct requestQuita {
       short code;
       string key_client;
    };

    struct requestInscribe {
       string name;
       string alias;
    };

    struct requestPlantilla {
       string key_client;
    };

    struct requestRepertorio {
       octet minimum;
    };

    struct requestJuega {
       string alias;
       short code;
    };

    struct requestTermina {
       string alias;
       short code;
    };

    struct requestLista {
       short code;
    };

    interface lsodtrp3 {

        void nuevo(in requestNuevo request, out Answer response);
        void quita(in requestQuita request, out Answer response);
        void inscribe(in requestInscribe request, out Answer response);
        void plantilla(in requestPlantilla request, out Answer response);
        void repertorio(in requestRepertorio request, out Answer response);
        void juega(in requestJuega request, out Answer response);
        void termina(in requestTermina request, out Answer response);
        void lista(in requestLista request, out Answer response);
    };
};
#endif
